server:
  port: 4040
  servlet:
    context-path: /boot
  tomcat:
    uri-encoding: utf-8


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/t?useSSL=false
    username: root
    password: omt2018
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapperLocations: classpath:mappers/*.xml

logging:
  config: classpath:log4j2.xml
